[package]
name = "notation_parser"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[[bin]]
name = "cli"
path = "src/bin/cli.rs"

[[bin]]
name = "data_generator"
path = "src/bin/data_generator.rs"
required-features = ["data_generation"]

[[bin]]
name = "get_vexflow_fsm"
path = "src/bin/get_vexflow_fsm.rs"

[[bin]]
name = "simple_test"
path = "src/bin/simple_test.rs"

[[bin]]
name = "debug_test"
path = "src/bin/debug_test.rs"

[[bin]]
name = "debug_unified"
path = "src/bin/debug_unified.rs"

[[bin]]
name = "debug_document_difference"
path = "src/bin/debug_document_difference.rs"

[[bin]]
name = "keystroke_test"
path = "src/bin/keystroke_test.rs"

[[bin]]
name = "quick_test"
path = "src/bin/quick_test.rs"

[[bin]]
name = "test_notation_detection"
path = "src/bin/test_notation_detection.rs"

[dependencies]
bs58 = "0.5.0"
console_error_panic_hook = "0.1.7"
fraction = "0.15.1"
js-sys = "0.3.69"
lazy_static = "1.4.0"
regex = "1.10.4"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
serde_json = "1.0.117"
serde_yaml = "0.9.34"
wasm-bindgen = { version = "0.2.92", features = ["serde-serialize"] }
serde_derive = "1.0"
clap = { version = "4.0", features = ["derive"] }
colored = "2.0"
mustache = "0.9.0"
rand = { version = "0.8.5", optional = true }
svg = { version = "0.14.0", optional = true }

[features]
data_generation = ["rand", "svg"]

[profile.release]
lto = true
