[package]
name = "music_text_parser"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[[bin]]
name = "cli"
path = "src/bin/cli.rs"

[[bin]]
name = "get_vexflow_fsm"
path = "src/bin/get_vexflow_fsm.rs"

[dependencies]
bs58 = "0.5.0"
console_error_panic_hook = "0.1.7"
fraction = "0.15.1"
js-sys = "0.3.69"
lazy_static = "1.4.0"
regex = "1.10.4"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
serde_json = "1.0.117"
serde_yaml = "0.9.34"
wasm-bindgen = { version = "0.2.92", features = ["serde-serialize"] }
serde_derive = "1.0"
clap = { version = "4.0", features = ["derive"] }
colored = "2.0"
mustache = "0.9.0"
rand = { version = "0.8.5", optional = true }
svg = { version = "0.14.0", optional = true }

[features]
data_generation = ["rand", "svg"]

[profile.dev]
opt-level = 0
debug = true
incremental = true

[profile.release]
lto = true

[package.metadata.wasm-pack.profile.dev]
wasm-opt = false

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
